import { GoogleGenAI } from "@google/genai";

export class LMStudioClient {
  private static instance: LMStudioClient;
  private ai: GoogleGenAI | null = null;

  private constructor() {
    if (process.env.GEMINI_API_KEY) {
      this.ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
    }
  }

  public static getInstance(): LMStudioClient {
    if (!LMStudioClient.instance) {
      LMStudioClient.instance = new LMStudioClient();
    }
    return LMStudioClient.instance;
  }

  public async complete(
    prompt: string,
    model: string = "local-model",
  ): Promise<string> {
    console.log(`[AI Interface] Routing prompt to AI: ${model}`);

    if (this.ai) {
       try {
         const response = await this.ai.models.generateContent({
           model: "gemini-2.5-flash",
           contents: prompt,
         });
         return response.text || "[No Content Generated by Gemini]";
       } catch (error) {
         console.warn("[AI Interface] Gemini API failed:", error);
         return `[AI Interface] Real AI Analysis unavailable due to error.`; 
       }
    }

    return `[System Note] To enable real AI text analysis, please configure GEMINI_API_KEY in the environment. Using generic placeholder for ${model}.`;
  }
}
